### ISSUE TITLE
SAGA NextGen is not available in Windows

### ISSUE THREAD

**Issue by PedroVenancio** [north-road/qgis-processing-saga-nextgen#1]
I was trying this new SAGA provider implementation in QGIS 3.6, on a Windows machine, but in Processing options I don't have the option to define the path to SAGA 7.2 binaries

![saga_next_gen_windows](https://user-images.githubusercontent.com/1331581/53881853-9c71ce00-400c-11e9-9437-3a4f64cfa521.jpg)

and maybe because of that, SAGA NextGen is not available in Processing Toolbox.

**Comment by palousegeo** [comment]
I have the same issue, Windows 10, QGIS 3.6.

**Comment by nyalldawson** [comment]
Fixed in 0.0.2 version
