### ISSUE TITLE
SAGA >= 9.1 needed but currently not optimally distributed

### ISSUE THREAD

**Issue by florisvdh** [north-road/qgis-processing-saga-nextgen#34]
The binary SAGA packages distributed through OSGeo4W (Windows) and ubuntugis-unstable PPA (Ubuntu) are lagging behind quite a lot, being [at 7.8.2](https://download.osgeo.org/osgeo4w/v2/x86_64/release/saga/) and [at 8.2.2](https://launchpad.net/%7Eubuntugis/+archive/ubuntu/ubuntugis-unstable/+index?field.series_filter=jammy) respectively. For Windows, an up-to-date binary build can be installed manually from https://sourceforge.net/projects/saga-gis/files/ while other platforms need to locally build from source to get it.

Currently users that make use of OSGeo4W / ubuntugis-unstable PPA (and perhaps other) repositories that distribute SAGA will get a warning after updating the plugin to version 1.0.0, like below.

Since the QGIS plugin now requests SAGA >= 9.1, I think it's a good idea to stimulate the OSGeo4W and the PPA maintainers to update SAGA in their repository.

```bash
$ qgis_process plugins
Problem with SAGA installation: unsupported SAGA version (found: 8.2.2, required: >=9.1.).
['PC_OUT', 'Result', None, 'True']
['PC', 'Point Cloud', None, 'True']
['PC_OUT', 'Colorised Point Cloud', None, 'False']
['THINNED_PC', 'Thinned Points', None, 'False']
['POINTS', 'Points', None, 'False']
['PC_OUT', 'Filtered Points', None, 'True']
['RESULT', 'Thinned Points', None, 'True']
['OUTPUT', 'Output', None, 'True']
['OUT', 'Output', None, 'False']
['POINTS', 'Points', None, 'True']
['TARGET_PC', 'Target', None, 'False']
['PC_OUT', 'Point Cloud Classified', None, 'True']
['POINTS', 'Points', None, 'False']
['POINTS', 'Points', None, 'False']
['PC_OUT', 'Point Cloud', None, 'True']
['PC_OUT', 'Result', None, 'True']
['TARGET_PC', 'Target', None, 'False']
['PC_OUT', 'Point Cloud', None, 'False']
['PC_OUT', 'Merged Point Cloud', None, 'False']
['POINTS', 'Points', None, 'False']
Available plugins
(* indicates loaded plugins which implement Processing providers)

* QNEAT3
* processing_saga_nextgen
* pcraster_tools
* ViewshedAnalysis
* cartography_tools
* wbt_for_qgis
* latlontools
* grassprovider
* otbprovider
* processing
```

**Comment by nyalldawson** [comment]
Thanks for raising this discussion @florisvdh !

> Since the QGIS plugin now requests SAGA >= 9.1, I think it's a good idea to stimulate the OSGeo4W and the PPA maintainers to update SAGA in their repository.

I agree wrt the Linux packagers, but is there really any need to update osgeo4w's version? I'd argue that it's ultimately deprecated and users should just use the official saga installer instead. (Ping @jef-n for thoughts!)

**Comment by florisvdh** [comment]
> need to update osgeo4w's version

I'm no Windows user, but on the QGIS download page using OSGeo4W is recommended to Windows users: _The OSGeo4W installer is recommended for regular users or organization deployments_. So I was assuming that's where they will usually get SAGA from as well (I have seen the OSGeo4W SAGA version pop up in {qgisprocess} issues a couple of times IIRC). I have not enough knowledge about OSGeo4W plans / aims to evaluate.

**Comment by florisvdh** [comment]
@kalxas I believe there's good reason here to update SAGA in the ubuntugis-unstable PPA, on order to satisfy the requirements of the SAGA processing provider in QGIS. It seems that a SAGA update is being prepared in OSGeo4W (https://github.com/jef-n/OSGeo4W/commit/4d63df4bd179f0be2188bbf26b9d631deb5ff705).

**Comment by jef-n** [comment]
saga9 is in osgeo4w and debian unstable.

**Comment by kalxas** [comment]
I will look at the latest saga version for UbuntuGIS

**Comment by benz0li** [comment]
@nyalldawson Thank you for updating the plugin to support SAGA GIS v9.1. Great work!

I have updated my Debian-based, multi-arch (`linux/amd64`, `linux/arm64`)

* [JupyterLab QGIS docker stack](https://github.com/b-data/jupyterlab-qgis-docker-stack)
* [JupyterLab R docker stack](https://github.com/b-data/jupyterlab-r-docker-stack)[^1]
* [Data Science Dev Containers](https://github.com/b-data/data-science-devcontainers)[^1]
    * based on [R docker stack](https://github.com/b-data/r-docker-stack)[^1]

with a [source build of SAGA GIS v9.1.3](https://gitlab.b-data.ch/saga-gis/saga-gissi/container_registry/526).  
ℹ️ The GPU accelerated (CUDA-enabled, Ubuntu-based) images remain at SAGA GIS v7.3.0 and plugin v0.0.7.

[^1]: `qgisprocess` image

**Comment by benz0li** [comment]
Running some tests with the `R qgisprocess` [Dev Container](https://containers.dev)

* on my MacBook Pro (M2 Max, `arm64`)
    * XQuartz installed
* using [VS Code](https://code.visualstudio.com)
* and [Docker Desktop](https://www.docker.com/products/docker-desktop/)

I found that executing `unset QT_QPA_PLATFORM; qgis`[^1] successfully starts QGIS in an X window[^2].

[^1]: `QT_QPA_PLATFORM` is set to `offscreen` by default in the `qgisprocess` images.
[^2]: Not using full resolution on 'high dpi'/retina displays.  
ℹ️ I.e. upscaled 1920 x 1080 instead of full 3840 x 2160 res.  
Cross reference: https://gitlab.freedesktop.org/xorg/xserver/-/issues/187

---

Can someone test, whether the same works

* on a Linux machine (`x86_64` or `AArch64`)
    * `xorg-server` installed
* using VS Code
* and Docker Desktop or [`docker-ce`](https://docs.docker.com/engine/install/#server)?

**Comment by roya0045** [comment]
On windows I am having issues with the plugin. It seems that launchin saga from '.\OSGeo4W\apps\saga9' is not fully functionnal as dll are missing.

Executing saga from ".\OSGeo4W\bin\saga9_gui.bat" works as intended as the missing dll are added in the paths.

My qgis installation is in osgeo4w so I'm not sure why I'm having issues with missing paths for osgeo dll.

osgeo installed was also never able to uninstall saga, strangely, but unrelated to the issue.

**Comment by feefladder** [comment]
Also on Windoze with OSGeo4W: Installing both saga and saga9:
![image](https://github.com/north-road/qgis-processing-saga-nextgen/assets/33122845/f1aa4470-b87b-4620-b787-6c1404cbaa97)
Then, it will use the saga7.8 version:
![image](https://github.com/north-road/qgis-processing-saga-nextgen/assets/33122845/4eed059c-bd4b-4a56-a247-69399058c2f2)
So, go into `C:\apps\` and rename `saga`->`saga7` and `saga9`->`saga`.
Alternatively, is there a way to tell this plugin where saga is installed?

**Comment by florisvdh** [comment]
> I will look at the latest saga version for UbuntuGIS

_Originally posted by @kalxas in https://github.com/north-road/qgis-processing-saga-nextgen/issues/34#issuecomment-1751785113_
            
Updates have been applied to the ubuntugis PPAs lately. The ubuntugis-unstable PPA now has a much more recent SAGA version! Thank you for the solution @kalxas.

```bash
$ apt policy saga
saga:
  Installed: 8.2.2+dfsg-1~jammy0
  Candidate: 9.3.0+dfsg-1~jammy0
  Version table:
     9.3.0+dfsg-1~jammy0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu jammy/main amd64 Packages
 *** 8.2.2+dfsg-1~jammy0 100
        100 /var/lib/dpkg/status
     7.3.0+dfsg-7 500
        500 http://ftp.belnet.be/ubuntu jammy/universe amd64 Packages
```

**Comment by VuOn7** [comment]
https://github.com/Geoinformatics-Lab/PyGILE-Plus/blob/main/docker/Dockerfile

This dockerfile  builds the Linux binary for 9.3.2 from source without issues. 

FYI it includes huge packages of QGIS, SAGA, GRASS, OTB, WBT and many DL and ML Python packages in a single docker image

I tried! WORKS FINE!
