### ISSUE TITLE
What is "Target area" in Saga Upslope area?

### ISSUE THREAD

**Issue by masjo84** [north-road/qgis-processing-saga-nextgen#42]
I´m using Saga upslope area in QGIS. Using the tool with target X, Y coordinates works fine but how to use "target area"? What kind of input raster is demanded and how does the tool use this input? I ‘we been searching a lot but can´t find any useful help.

![Skärmbild 2024-01-30 143341](https://github.com/north-road/qgis-processing-saga-nextgen/assets/158172553/edb15efd-d3a1-48c4-bcbe-8d65bed9ba87)

**Comment by baswein** [comment]
Masjo84 this is the Github page for the QGIS SAGA plugin and I think that your question is a more general SAGA question and you are more likely to find an answer on the SAGA forum https://sourceforge.net/p/saga-gis/discussion/790705/.  That said unfortunately SAGA does not have extensive documentation. The tool doc is here but is not clarifying: https://saga-gis.sourceforge.io/saga_tool_doc/7.6.3/ta_hydrology_4.html
However this webpage might be helpful: 
https://saga-gis.sourceforge.io/saga_tool_doc/7.6.3/ta_hydrology_4.html
It would be nice of you to mark this as closed as it is not an issue with the functioning of the plugin. Thanks -Bas

**Comment by masjo84** [comment]
Thank you for response baswein! I will mark the issue as closed. By the way I found out that the tool accepts various raster values as long as the extent is the same as the elevation raster.
